In [87]:
import pandas as pd
import numpy as np
import math
import operator

In [88]:
data = pd.read_csv("iris.csv",header=None,names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])
data

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [89]:
x_data = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
x_data = x_data.apply(lambda x: (x-x.min(axis=0)) / (x.max(axis=0)-(x.min(axis=0))))
x_data

     sepal_length  sepal_width  petal_length  petal_width
0        0.222222     0.625000      0.067797     0.041667
1        0.166667     0.416667      0.067797     0.041667
2        0.111111     0.500000      0.050847     0.041667
3        0.083333     0.458333      0.084746     0.041667
4        0.194444     0.666667      0.067797     0.041667
..            ...          ...           ...          ...
145      0.666667     0.416667      0.711864     0.916667
146      0.555556     0.208333      0.677966     0.750000
147      0.611111     0.416667      0.711864     0.791667
148      0.527778     0.583333      0.745763     0.916667
149      0.444444     0.416667      0.694915     0.708333

[150 rows x 4 columns]

In [97]:
testInstance = np.array([[5.1,2.5,3.2,4.3],[4.9,3.1,1.4,0.2],[6,3,4.8,1.8]])
trainingSet = data

In [98]:
def euclidianDistance(data1, data2, length):
    distance = 0
    for x in range(length):
        distance += np.square(data1[x] - data2[x])
       
    return np.sqrt(distance)
def knn(trainingSet, testInstance, k):
 
    distances = {}
    sort = {}
length = testInstance.shape[1]
print(length)
    
    
# Calculating euclidean distance between each row of training data and test data
for x in range(len(trainingSet)):
    dist = euclidianDistance(testInstance, trainingSet.iloc[x], length)
distances[x] = dist[0]

# Sorting them on the basis of distance
sorted_d = sorted(distances.items(), key=operator.itemgetter(1)) #by using it we store indices also
sorted_d1 = sorted(distances.items())
print(sorted_d[:5])
print(sorted_d1[:5])
   
 
neighbors = []
    
    
# Extracting top k neighbors
for x in range(k):
    neighbors.append(sorted_d[x][0])
counts = {"Iris-setosa":0,"Iris-versicolor":0,"Iris-virginica":0}
    
    
# Calculating the most freq class in the neighbors
for x in range(len(neighbors)):
    response = trainingSet.iloc[neighbors[x]][-1]
 
    if response in counts:
        counts[response] += 1
    else:
        counts[response] = 1
  
print(counts)
sortedVotes = sorted(counts.items(), key=operator.itemgetter(1), reverse=True)
print(sortedVotes)
return(sortedVotes[0][0], neighbors)

4

IndexError: index 3 is out of bounds for axis 0 with size 3